create e2e against staging env

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,10 +18,50 @@ jobs:
       - run: npm test
       - run: npm run build
 
-  build-and-push:
+  deploy-render:
     needs: unit-tests
     if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
+    environment:
+      name: render
+    env:
+      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
+    steps:
+      - name: Trigger Render deploy
+        run: |
+          response=$(curl -s -w "%{http_code}" -o /dev/null -X POST "$RENDER_DEPLOY_HOOK")
+          if [ "$response" -eq 200 ]; then
+            echo "Render deploy triggered successfully."
+          else
+            echo "Failed to trigger Render deploy. HTTP status: $response"
+            exit 1
+          fi
+  
+  e2e-tests:
+    needs: deploy-render
+    if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    environment:
+      name: aws
+    env:
+      API_BASE_URL: https://staging.yourapp.com
+      TEST_USER: giorgosts
+      TEST_PASS: tsantekidis
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+      - run: npm install
+      - run: npm run e2e-tests
+  
+  build-and-push:
+    needs: e2e-tests
+    if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
+    runs-on: ubuntu-latest
+    environment:
+      name: aws
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -45,66 +85,8 @@ jobs:
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-  # Build-Push-Image-Dockerhub:
-  #   needs: unit-tests
-  #   if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
-
-  #     - name: Login to Docker Hub
-  #       uses: docker/login-action@v2
-  #       with:
-  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
-  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
-
-  #     - name: Build and Push Docker Image
-  #       uses: docker/build-push-action@v4
-  #       with:
-  #         context: .
-  #         push: true
-  #         tags: |
-  #           tsandas/sirius-crm-server:${{ github.sha }}
-  #           tsandas/sirius-crm-server:latest
-
-  # deploy-koyeb:
-  #   needs: unit-tests
-  #   if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
-  #   runs-on: ubuntu-latest
-  #   environment:
-  #     name: koyeb
-  #   env:
-  #     KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
-  #   steps:
-  #     - name: Deploy
-  #       run: |
-  #         curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
-  #         export PATH=$HOME/.koyeb/bin:$PATH
-  #         koyeb services redeploy sirius-crm/sirius-crm-server --token $KOYEB_API_TOKEN
-  #         koyeb services update sirius-crm/sirius-crm-server --git-sha ${{ github.sha }} --token $KOYEB_API_TOKEN
-  
-  deploy-render:
-    needs: unit-tests
-    if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
-    runs-on: ubuntu-latest
-    environment:
-      name: render
-    env:
-      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
-    steps:
-      - name: Trigger Render deploy
-        run: |
-          response=$(curl -s -w "%{http_code}" -o /dev/null -X POST "$RENDER_DEPLOY_HOOK")
-          if [ "$response" -eq 200 ]; then
-            echo "Render deploy triggered successfully."
-          else
-            echo "Failed to trigger Render deploy. HTTP status: $response"
-            exit 1
-          fi
-
   deploy-aws:
-    needs: build-and-push
+    needs: e2e-tests
     if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
     runs-on: ubuntu-latest
     environment:
